#!/bin/sh

START_ADDR=00100000

function usage {
    echo "Usage $0 file ttydev";
    echo "      $0 -h  prints this message"
    exit -1;
}


# function to draw a progress bar
function progress {
    PROC=$1
    while [ -d /proc/$PROC ];do
        echo -n '.' ; sleep 0.2
    done
    echo " DONE"
    return 0
}


[[ $1 = "-h" ]] && usage
[[ $# -ne 2 ]] &&  echo "Bad arguments" && usage

FILE=$1
TTY=$2

[[ ! -f $FILE ]] && echo "Bad program file" && usage
[[ ! -c $TTY ]]  && echo "Bad tty device"   && usage

SIZE=`stat -c%s $FILE`
SIZEX=`printf "%08x" $[$SIZE/2]`
SIZE=`printf "%u" $[$SIZE/2]`

echo "Uploading file $FILE  to $TTY :"
echo "               start address 0x$START_ADDR"
echo "               file size     0x$SIZEX ($SIZE byte)"
# command to load soft
echo -n "u${START_ADDR}${SIZEX}"> $TTY
echo -n ".."

# upload program file
# this is done in background
cat $FILE > $TTY &
# draw a progress bar as long as the transfert isn't finiched
progress $!

echo "" > $TTY

echo "Starting program"
# command to go to start address
echo -n "g${START_ADDR}"> $TTY
